Attempts writing my webpack config file
AJAT-Request/photocarousel pull request #4
Opened 2018-09-11 05:13 UTC by macandrew6

hi @jverch can you please review my webpack config file?

2018-09-11 15:48 UTC, jverch commented on webpack.config.js
> +        test: /\.(js?)$/,
I believe it needs to be jsx? here since the ? means the previous character (x) is optional, so it will look at both js files and jsx files.

2018-09-11 15:48 UTC, jverch commented on webpack.config.js
> +        queery: {
'query'

2018-09-11 15:53 UTC, jverch requested changes
I made a few requests for changes, please look over them!

2018-09-12 01:04 UTC, macandrew6 commented on webpack.config.js
> +        test: /\.(js?)$/,
ahh okay thanks!

2018-09-12 01:05 UTC, macandrew6 commented on webpack.config.js
> +        queery: {
lol thanks!!

2018-09-12 01:05 UTC, merged